apiVersion: 1

contactPoints:
  - orgId: 1
    name: incident-responder
    receivers:
      - uid: incident-responder-webhook
        type: webhook
        settings:
          url: http://localhost:8001/alerts
          httpMethod: POST
        disableResolveMessage: false